name: not
description: "A new Flutter project."


publish_to: 'none'







version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'






dependencies:
  flutter:
    sdk: flutter
  flutter_pdfview: ^1.3.2
  image_picker: ^1.1.0
  camera: ^0.10.5+9
  path: ^1.9.0
  path_provider: ^2.1.3

  google_mlkit_text_recognition:
    path: ../google_mlkit_text_recognition


dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter

























